export const fetchDevices = async () => {
    return [
      { id: 1, device: "Optical Power Meter #1", status: "Online", value: "-12.4 dBm" },
      { id: 2, device: "Spectrum Analyzer #2", status: "Online", value: "-45.1 dBm" },
      { id: 3, device: "Signal Analyzer #3", status: "Offline", value: "N/A" },
      { id: 4, device: "Network Analyzer #4", status: "Online", value: "-30.7 dBm" },
      { id: 5, device: "RF Generator #5", status: "Online", value: "-21.3 dBm" },
      { id: 6, device: "Digital Oscilloscope #6", status: "Offline", value: "N/A" },
      { id: 7, device: "Vector Signal Analyzer #7", status: "Online", value: "-15.2 dBm" },
      { id: 8, device: "Frequency Counter #8", status: "Online", value: "-9.7 dBm" },
      { id: 9, device: "Signal Generator #9", status: "Online", value: "-18.9 dBm" },
      { id: 10, device: "Optical Spectrum Analyzer #10", status: "Offline", value: "N/A" },
  
      { id: 11, device: "Optical Power Meter #11", status: "Online", value: "-11.5 dBm" },
      { id: 12, device: "Spectrum Analyzer #12", status: "Online", value: "-40.2 dBm" },
      { id: 13, device: "Signal Analyzer #13", status: "Offline", value: "N/A" },
      { id: 14, device: "Network Analyzer #14", status: "Online", value: "-29.1 dBm" },
      { id: 15, device: "RF Generator #15", status: "Online", value: "-24.4 dBm" },
      { id: 16, device: "Digital Oscilloscope #16", status: "Offline", value: "N/A" },
      { id: 17, device: "Vector Signal Analyzer #17", status: "Online", value: "-16.6 dBm" },
      { id: 18, device: "Frequency Counter #18", status: "Online", value: "-7.8 dBm" },
      { id: 19, device: "Signal Generator #19", status: "Online", value: "-19.3 dBm" },
      { id: 20, device: "Optical Spectrum Analyzer #20", status: "Offline", value: "N/A" },
  
      { id: 21, device: "Optical Power Meter #21", status: "Online", value: "-10.5 dBm" },
      { id: 22, device: "Spectrum Analyzer #22", status: "Online", value: "-42.8 dBm" },
      { id: 23, device: "Signal Analyzer #23", status: "Offline", value: "N/A" },
      { id: 24, device: "Network Analyzer #24", status: "Online", value: "-31.0 dBm" },
      { id: 25, device: "RF Generator #25", status: "Online", value: "-22.2 dBm" },
      { id: 26, device: "Digital Oscilloscope #26", status: "Offline", value: "N/A" },
      { id: 27, device: "Vector Signal Analyzer #27", status: "Online", value: "-17.4 dBm" },
      { id: 28, device: "Frequency Counter #28", status: "Online", value: "-6.9 dBm" },
      { id: 29, device: "Signal Generator #29", status: "Online", value: "-20.0 dBm" },
      { id: 30, device: "Optical Spectrum Analyzer #30", status: "Offline", value: "N/A" },
  
      { id: 31, device: "Optical Power Meter #31", status: "Online", value: "-13.2 dBm" },
      { id: 32, device: "Spectrum Analyzer #32", status: "Online", value: "-38.7 dBm" },
      { id: 33, device: "Signal Analyzer #33", status: "Offline", value: "N/A" },
      { id: 34, device: "Network Analyzer #34", status: "Online", value: "-28.4 dBm" },
      { id: 35, device: "RF Generator #35", status: "Online", value: "-23.1 dBm" },
      { id: 36, device: "Digital Oscilloscope #36", status: "Offline", value: "N/A" },
      { id: 37, device: "Vector Signal Analyzer #37", status: "Online", value: "-14.9 dBm" },
      { id: 38, device: "Frequency Counter #38", status: "Online", value: "-8.3 dBm" },
      { id: 39, device: "Signal Generator #39", status: "Online", value: "-21.0 dBm" },
      { id: 40, device: "Optical Spectrum Analyzer #40", status: "Offline", value: "N/A" },
  
      { id: 41, device: "Optical Power Meter #41", status: "Online", value: "-12.7 dBm" },
      { id: 42, device: "Spectrum Analyzer #42", status: "Online", value: "-44.1 dBm" },
      { id: 43, device: "Signal Analyzer #43", status: "Offline", value: "N/A" },
      { id: 44, device: "Network Analyzer #44", status: "Online", value: "-27.9 dBm" },
      { id: 45, device: "RF Generator #45", status: "Online", value: "-22.7 dBm" },
      { id: 46, device: "Digital Oscilloscope #46", status: "Offline", value: "N/A" },
      { id: 47, device: "Vector Signal Analyzer #47", status: "Online", value: "-18.5 dBm" },
      { id: 48, device: "Frequency Counter #48", status: "Online", value: "-6.1 dBm" },
      { id: 49, device: "Signal Generator #49", status: "Online", value: "-20.5 dBm" },
      { id: 50, device: "Optical Spectrum Analyzer #50", status: "Offline", value: "N/A" },
  
      { id: 51, device: "Optical Power Meter #51", status: "Online", value: "-11.9 dBm" },
      { id: 52, device: "Spectrum Analyzer #52", status: "Online", value: "-39.6 dBm" },
      { id: 53, device: "Signal Analyzer #53", status: "Offline", value: "N/A" },
      { id: 54, device: "Network Analyzer #54", status: "Online", value: "-29.8 dBm" },
      { id: 55, device: "RF Generator #55", status: "Online", value: "-24.9 dBm" },
      { id: 56, device: "Digital Oscilloscope #56", status: "Offline", value: "N/A" },
      { id: 57, device: "Vector Signal Analyzer #57", status: "Online", value: "-16.2 dBm" },
      { id: 58, device: "Frequency Counter #58", status: "Online", value: "-9.1 dBm" },
      { id: 59, device: "Signal Generator #59", status: "Online", value: "-19.7 dBm" },
      { id: 60, device: "Optical Spectrum Analyzer #60", status: "Offline", value: "N/A" },
  
      { id: 61, device: "Optical Power Meter #61", status: "Online", value: "-10.9 dBm" },
      { id: 62, device: "Spectrum Analyzer #62", status: "Online", value: "-41.5 dBm" },
      { id: 63, device: "Signal Analyzer #63", status: "Offline", value: "N/A" },
      { id: 64, device: "Network Analyzer #64", status: "Online", value: "-30.2 dBm" },
      { id: 65, device: "RF Generator #65", status: "Online", value: "-23.8 dBm" },
      { id: 66, device: "Digital Oscilloscope #66", status: "Offline", value: "N/A" },
      { id: 67, device: "Vector Signal Analyzer #67", status: "Online", value: "-17.7 dBm" },
      { id: 68, device: "Frequency Counter #68", status: "Online", value: "-7.2 dBm" },
      { id: 69, device: "Signal Generator #69", status: "Online", value: "-21.4 dBm" },
      { id: 70, device: "Optical Spectrum Analyzer #70", status: "Offline", value: "N/A" },
  
      { id: 71, device: "Optical Power Meter #71", status: "Online", value: "-12.2 dBm" },
      { id: 72, device: "Spectrum Analyzer #72", status: "Online", value: "-43.6 dBm" },
      { id: 73, device: "Signal Analyzer #73", status: "Offline", value: "N/A" },
      { id: 74, device: "Network Analyzer #74", status: "Online", value: "-28.9 dBm" },
      { id: 75, device: "RF Generator #75", status: "Online", value: "-22.6 dBm" },
      { id: 76, device: "Digital Oscilloscope #76", status: "Offline", value: "N/A" },
      { id: 77, device: "Vector Signal Analyzer #77", status: "Online", value: "-15.4 dBm" },
      { id: 78, device: "Frequency Counter #78", status: "Online", value: "-8.8 dBm" },
      { id: 79, device: "Signal Generator #79", status: "Online", value: "-19.2 dBm" },
      { id: 80, device: "Optical Spectrum Analyzer #80", status: "Offline", value: "N/A" },
  
      { id: 81, device: "Optical Power Meter #81", status: "Online", value: "-11.1 dBm" },
      { id: 82, device: "Spectrum Analyzer #82", status: "Online", value: "-40.7 dBm" },
      { id: 83, device: "Signal Analyzer #83", status: "Offline", value: "N/A" },
      { id: 84, device: "Network Analyzer #84", status: "Online", value: "-29.5 dBm" },
      { id: 85, device: "RF Generator #85", status: "Online", value: "-23.4 dBm" },
      { id: 86, device: "Digital Oscilloscope #86", status: "Offline", value: "N/A" },
      { id: 87, device: "Vector Signal Analyzer #87", status: "Online", value: "-16.9 dBm" },
      { id: 88, device: "Frequency Counter #88", status: "Online", value: "-7.5 dBm" },
      { id: 89, device: "Signal Generator #89", status: "Online", value: "-20.3 dBm" },
      { id: 90, device: "Optical Spectrum Analyzer #90", status: "Offline", value: "N/A" },
  
      { id: 91, device: "Optical Power Meter #91", status: "Online", value: "-12.8 dBm" },
      { id: 92, device: "Spectrum Analyzer #92", status: "Online", value: "-42.2 dBm" },
      { id: 93, device: "Signal Analyzer #93", status: "Offline", value: "N/A" },
      { id: 94, device: "Network Analyzer #94", status: "Online", value: "-28.3 dBm" },
      { id: 95, device: "RF Generator #95", status: "Online", value: "-22.9 dBm" },
      { id: 96, device: "Digital Oscilloscope #96", status: "Offline", value: "N/A" },
      { id: 97, device: "Vector Signal Analyzer #97", status: "Online", value: "-15.7 dBm" },
      { id: 98, device: "Frequency Counter #98", status: "Online", value: "-6.4 dBm" },
      { id: 99, device: "Signal Generator #99", status: "Online", value: "-19.8 dBm" },
      { id: 100, device: "Optical Spectrum Analyzer #100", status: "Offline", value: "N/A" }
    ];
  };